enum ExchangeStatus {
    EXCHANGE_STATUS_UNSPECIFIED = 0,
    EXCHANGE_STATUS_WAITING = 1,
    EXCHANGE_STATUS_CANCEL_BY_USER = 2,
    EXCHANGE_STATUS_PENDING = 3,
    EXCHANGE_STATUS_DONE = 4,
    EXCHANGE_STATUS_REJECT = 5,
}