enum GiftCodeError {
  GIFT_CODE_ERROR_UNSPECIFIED = 0,
  GIFT_CODE_ERROR_NOT_OPEN = 1,
  GIFT_CODE_ERROR_HAS_CLOSED = 2,
  GIFT_CODE_ERROR_REACH_MAX_CLAIMED = 3,
  GIFT_CODE_ERROR_ALREADY_CLAIMED = 4,
  GIFT_CODE_ERROR_LV_VIP_NOT_MEET_REQUIRE = 5,
}
