enum HistoryRewardTime {
    HISTORY_REWARD_TIME_UNSPECIFIED = 0,
    HISTORY_REWARD_TIME_THIS_WEEK = 1,
    HISTORY_REWARD_TIME_LAST_WEEK = 2,
    HISTORY_REWARD_TIME_THIS_MONTH = 3,
    HISTORY_REWARD_TIME_LAST_MONTH = 4,
}