syntax = "proto3";

// The realtime protocol for the template match engine.
package proto;

option go_package = "github.com/nk-nigeria/cgp-common/proto";


message ChangePasswordRequest {
  string old_password = 1;
  string password = 2;
}

message RegisterRequest {
  string user_name = 1;
  string password = 2;
}

message Profile {
  string user_id = 1;
  string user_name = 2;
  string display_name = 3;
  string avatar_url = 4;
  string status = 5;
  int64 account_chip = 6;
  int64 bank_chip = 7;
  string ref_code = 8;
  string lang_tag = 9;
  string link_group = 10;
  string link_fanpage_fb = 11;
  string app_config = 12;
  string avatar_id = 13;
  bool registrable = 14;
  int64 vip_level = 15;
  int64 last_online_time_unix = 16;
  int64 create_time_unix = 17;
  int64 remain_time_input_ref_code = 18;
  repeated LangCode lang_availables = 19;
  PlayingMatch playing_match = 20;
  string device_id = 21;
  string last_device_id = 22;
  string ref_game = 23;
  string current_ip = 24;
  int64 vip_point = 25;
  bool is_online = 26;
  bool is_banned = 27;
  int64 last_login_unix = 28;
  int64 user_sid = 29;
  repeated FeatureName allowed_features = 30;
}

enum FeatureName {
  FEATURE_UNSPECIFIED = 0;

  // Login category
  FEATURE_QUICK_LOGIN = 1;              // Login nhanh
  FEATURE_LOGIN_USERNAME_PASS = 2;      // Login username/pass

  // Lobby category
  FEATURE_SUPPORT = 10;                 // Support
  FEATURE_PROFILE = 11;                 // Profile
  FEATURE_SHOP = 12;                    // Shop
  FEATURE_NEWS = 13;                    // News
  FEATURE_SETTING = 14;                 // Setting
  FEATURE_CHECK_IN_ONLINE = 15;          // Check_in Online
  FEATURE_FREE_CHIP = 16;               // FreeChip
  FEATURE_MAIL = 17;                    // Mail
  FEATURE_RANK = 18;                    // Rank
  FEATURE_GIFT_CODE = 19;               // Gift Code
  FEATURE_BANK = 20;                    // Bank
  FEATURE_CHAT_WORLD = 21;              // Chat World
  FEATURE_CHAT_TABLE = 22;              // Chat Table
  FEATURE_EXCHANGE = 23;                // Exchange
  FEATURE_TIN_NONG_POPUP = 24;          // Tin nóng Popup
  FEATURE_NEW_BANNER = 25;              // New banner
  FEATURE_QUICK_PLAY = 26;              // Quick Play
  FEATURE_VIP_FARM = 27;                // Vip's Farm
  FEATURE_SETTING_ACCOUNT_DELETION = 28; // Setting - Account Deletion

  // Vào sảnh chọn mức cược
  FEATURE_SELECT_BET = 30;              // Select Bet
  FEATURE_SELECT_TABLE = 31;            // Select Table

  // Join bàn
  FEATURE_CHECK_DOC = 40;               // Check DOC, với từng game
}

message PlayingMatch {
  string code = 1;
  string match_id = 2;
  int64 leave_time = 3;
  int64 mcb=4;
  int64 bet=5;
}

message ListProfile {
  repeated Profile profiles = 1;
}

message SimpleProfile {
  string user_id = 1;
  string user_name = 2;
  string display_name = 3;
  string status = 4;
  int64 account_chip = 5;
  string avatar_id = 6;
  int64 vip_level = 7;
  PlayingMatch playing_match = 8;
  int64 user_sid = 9;
}

message ListSimpleProfile {
  repeated SimpleProfile profiles = 1;
}

message QuickChatUpdateRequest {
  repeated string texts = 1;
}

message QuickChatResponse {
  repeated string texts = 1;
}

message LangCode {
  string iso_code = 1;
  string display_name = 2;
  string source_url = 3;
}
