// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: color_game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Api {

  /// <summary>Holder for reflection information generated from color_game.proto</summary>
  public static partial class ColorGameReflection {

    #region Descriptor
    /// <summary>File descriptor for color_game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ColorGameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBjb2xvcl9nYW1lLnByb3RvEgNhcGkiSAoJQmV0UmVzdWx0Eg8KB3VzZXJf",
            "aWQYASABKAkSGgoEYmV0cxgCIAMoCzIMLmFwaS5JbmZvQmV0Eg4KBmlzX3dp",
            "bhgDIAEoCCKDAQoPQ29sb3JHYW1lRmluaXNoEiIKCnJvbGxfY29sb3IYASAB",
            "KAsyDi5hcGkuTGlzdENvbG9yEiMKC2JldF9yZXN1bHRzGAIgAygLMg4uYXBp",
            "LkJldFJlc3VsdBInCg1oaXN0b3J5X3JvbGxzGAMgASgLMhAuYXBpLkhpc3Rv",
            "cnlSb2xsIhsKCUxpc3RDb2xvchIOCgZjb2xvcnMYASADKAUiKAoJUmF0ZUNv",
            "bG9yEgoKAmlkGAEgASgFEg8KB3BlcmNlbnQYAiABKAUiVwoLSGlzdG9yeVJv",
            "bGwSIwoLbGlzdF9jb2xvcnMYASADKAsyDi5hcGkuTGlzdENvbG9yEiMKC3Jh",
            "dGVfY29sb3JzGAIgAygLMg4uYXBpLlJhdGVDb2xvciKUAQoHSW5mb0JldBIK",
            "CgJpZBgBIAEoBRINCgVjaGlwcxgCIAEoAxISCgpuX3VzZXJfYmV0GAMgASgF",
            "EgwKBGRlc3AYBCABKAkSFQoNcmVxX3NwZWNfZ2FtZRgFIAEoBRIaChJlbWl0",
            "X25ld2dhbWVfZXZlbnQYBiABKAgSGQoRZGVsYXlfZW1pdF9yZXN1bHQYByAB",
            "KAkiLgoLTGlzdEluZm9CZXQSHwoJbGlzdF9iZXRzGAEgAygLMgwuYXBpLklu",
            "Zm9CZXQi2gEKClVwZGF0ZURlc2sSEAoIbl9wbGF5ZXIYASABKAUSGAoQdXBk",
            "YXRlX3VzZXJfYmV0cxgCIAEoCBIYChB1cGRhdGVfY2VsbF9iZXRzGAMgASgI",
            "Eh8KCXVzZXJfYmV0cxgEIAMoCzIMLmFwaS5JbmZvQmV0Eh8KCWNlbGxfYmV0",
            "cxgFIAMoCzIMLmFwaS5JbmZvQmV0EhsKE3VwZGF0ZV9oaXN0b3J5X3JvbGwY",
            "BiABKAgSJwoNaGlzdG9yeV9yb2xscxgHIAEoCzIQLmFwaS5IaXN0b3J5Um9s",
            "bCqBAQoFQ29sb3ISFQoRQ09MT1JfVU5TUEVDSUZJRUQQABIQCgxDT0xPUl9Z",
            "RUxMT1cQARIPCgtDT0xPUl9XSElURRACEg4KCkNPTE9SX1BJTksQBBIOCgpD",
            "T0xPUl9CTFVFEAgSDQoJQ09MT1JfUkVEEBASDwoLQ09MT1JfR1JFRU4QIEIw",
            "Wi5naXRodWIuY29tL25ha2FtYUZyYW1ld29yay9jZ3AtYmluZy1tb2R1bGUv",
            "YXBpYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Api.Color), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.BetResult), global::Api.BetResult.Parser, new[]{ "UserId", "Bets", "IsWin" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.ColorGameFinish), global::Api.ColorGameFinish.Parser, new[]{ "RollColor", "BetResults", "HistoryRolls" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.ListColor), global::Api.ListColor.Parser, new[]{ "Colors" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.RateColor), global::Api.RateColor.Parser, new[]{ "Id", "Percent" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.HistoryRoll), global::Api.HistoryRoll.Parser, new[]{ "ListColors", "RateColors" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.InfoBet), global::Api.InfoBet.Parser, new[]{ "Id", "Chips", "NUserBet", "Desp", "ReqSpecGame", "EmitNewgameEvent", "DelayEmitResult" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.ListInfoBet), global::Api.ListInfoBet.Parser, new[]{ "ListBets" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Api.UpdateDesk), global::Api.UpdateDesk.Parser, new[]{ "NPlayer", "UpdateUserBets", "UpdateCellBets", "UserBets", "CellBets", "UpdateHistoryRoll", "HistoryRolls" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Color {
    [pbr::OriginalName("COLOR_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("COLOR_YELLOW")] Yellow = 1,
    [pbr::OriginalName("COLOR_WHITE")] White = 2,
    [pbr::OriginalName("COLOR_PINK")] Pink = 4,
    [pbr::OriginalName("COLOR_BLUE")] Blue = 8,
    [pbr::OriginalName("COLOR_RED")] Red = 16,
    [pbr::OriginalName("COLOR_GREEN")] Green = 32,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BetResult : pb::IMessage<BetResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BetResult> _parser = new pb::MessageParser<BetResult>(() => new BetResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BetResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BetResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BetResult(BetResult other) : this() {
      userId_ = other.userId_;
      bets_ = other.bets_.Clone();
      isWin_ = other.isWin_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BetResult Clone() {
      return new BetResult(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bets" field.</summary>
    public const int BetsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Api.InfoBet> _repeated_bets_codec
        = pb::FieldCodec.ForMessage(18, global::Api.InfoBet.Parser);
    private readonly pbc::RepeatedField<global::Api.InfoBet> bets_ = new pbc::RepeatedField<global::Api.InfoBet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.InfoBet> Bets {
      get { return bets_; }
    }

    /// <summary>Field number for the "is_win" field.</summary>
    public const int IsWinFieldNumber = 3;
    private bool isWin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsWin {
      get { return isWin_; }
      set {
        isWin_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BetResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BetResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if(!bets_.Equals(other.bets_)) return false;
      if (IsWin != other.IsWin) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      hash ^= bets_.GetHashCode();
      if (IsWin != false) hash ^= IsWin.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      bets_.WriteTo(output, _repeated_bets_codec);
      if (IsWin != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsWin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      bets_.WriteTo(ref output, _repeated_bets_codec);
      if (IsWin != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsWin);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      size += bets_.CalculateSize(_repeated_bets_codec);
      if (IsWin != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BetResult other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      bets_.Add(other.bets_);
      if (other.IsWin != false) {
        IsWin = other.IsWin;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            bets_.AddEntriesFrom(input, _repeated_bets_codec);
            break;
          }
          case 24: {
            IsWin = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 18: {
            bets_.AddEntriesFrom(ref input, _repeated_bets_codec);
            break;
          }
          case 24: {
            IsWin = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ColorGameFinish : pb::IMessage<ColorGameFinish>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ColorGameFinish> _parser = new pb::MessageParser<ColorGameFinish>(() => new ColorGameFinish());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ColorGameFinish> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorGameFinish() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorGameFinish(ColorGameFinish other) : this() {
      rollColor_ = other.rollColor_ != null ? other.rollColor_.Clone() : null;
      betResults_ = other.betResults_.Clone();
      historyRolls_ = other.historyRolls_ != null ? other.historyRolls_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ColorGameFinish Clone() {
      return new ColorGameFinish(this);
    }

    /// <summary>Field number for the "roll_color" field.</summary>
    public const int RollColorFieldNumber = 1;
    private global::Api.ListColor rollColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.ListColor RollColor {
      get { return rollColor_; }
      set {
        rollColor_ = value;
      }
    }

    /// <summary>Field number for the "bet_results" field.</summary>
    public const int BetResultsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Api.BetResult> _repeated_betResults_codec
        = pb::FieldCodec.ForMessage(18, global::Api.BetResult.Parser);
    private readonly pbc::RepeatedField<global::Api.BetResult> betResults_ = new pbc::RepeatedField<global::Api.BetResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.BetResult> BetResults {
      get { return betResults_; }
    }

    /// <summary>Field number for the "history_rolls" field.</summary>
    public const int HistoryRollsFieldNumber = 3;
    private global::Api.HistoryRoll historyRolls_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.HistoryRoll HistoryRolls {
      get { return historyRolls_; }
      set {
        historyRolls_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ColorGameFinish);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ColorGameFinish other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(RollColor, other.RollColor)) return false;
      if(!betResults_.Equals(other.betResults_)) return false;
      if (!object.Equals(HistoryRolls, other.HistoryRolls)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (rollColor_ != null) hash ^= RollColor.GetHashCode();
      hash ^= betResults_.GetHashCode();
      if (historyRolls_ != null) hash ^= HistoryRolls.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (rollColor_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RollColor);
      }
      betResults_.WriteTo(output, _repeated_betResults_codec);
      if (historyRolls_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HistoryRolls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (rollColor_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(RollColor);
      }
      betResults_.WriteTo(ref output, _repeated_betResults_codec);
      if (historyRolls_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(HistoryRolls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (rollColor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RollColor);
      }
      size += betResults_.CalculateSize(_repeated_betResults_codec);
      if (historyRolls_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HistoryRolls);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ColorGameFinish other) {
      if (other == null) {
        return;
      }
      if (other.rollColor_ != null) {
        if (rollColor_ == null) {
          RollColor = new global::Api.ListColor();
        }
        RollColor.MergeFrom(other.RollColor);
      }
      betResults_.Add(other.betResults_);
      if (other.historyRolls_ != null) {
        if (historyRolls_ == null) {
          HistoryRolls = new global::Api.HistoryRoll();
        }
        HistoryRolls.MergeFrom(other.HistoryRolls);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (rollColor_ == null) {
              RollColor = new global::Api.ListColor();
            }
            input.ReadMessage(RollColor);
            break;
          }
          case 18: {
            betResults_.AddEntriesFrom(input, _repeated_betResults_codec);
            break;
          }
          case 26: {
            if (historyRolls_ == null) {
              HistoryRolls = new global::Api.HistoryRoll();
            }
            input.ReadMessage(HistoryRolls);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (rollColor_ == null) {
              RollColor = new global::Api.ListColor();
            }
            input.ReadMessage(RollColor);
            break;
          }
          case 18: {
            betResults_.AddEntriesFrom(ref input, _repeated_betResults_codec);
            break;
          }
          case 26: {
            if (historyRolls_ == null) {
              HistoryRolls = new global::Api.HistoryRoll();
            }
            input.ReadMessage(HistoryRolls);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ListColor : pb::IMessage<ListColor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ListColor> _parser = new pb::MessageParser<ListColor>(() => new ListColor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ListColor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListColor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListColor(ListColor other) : this() {
      colors_ = other.colors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListColor Clone() {
      return new ListColor(this);
    }

    /// <summary>Field number for the "colors" field.</summary>
    public const int ColorsFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_colors_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> colors_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Colors {
      get { return colors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ListColor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ListColor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!colors_.Equals(other.colors_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= colors_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      colors_.WriteTo(output, _repeated_colors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      colors_.WriteTo(ref output, _repeated_colors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += colors_.CalculateSize(_repeated_colors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ListColor other) {
      if (other == null) {
        return;
      }
      colors_.Add(other.colors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            colors_.AddEntriesFrom(input, _repeated_colors_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            colors_.AddEntriesFrom(ref input, _repeated_colors_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RateColor : pb::IMessage<RateColor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RateColor> _parser = new pb::MessageParser<RateColor>(() => new RateColor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RateColor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RateColor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RateColor(RateColor other) : this() {
      id_ = other.id_;
      percent_ = other.percent_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RateColor Clone() {
      return new RateColor(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "percent" field.</summary>
    public const int PercentFieldNumber = 2;
    private int percent_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Percent {
      get { return percent_; }
      set {
        percent_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RateColor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RateColor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Percent != other.Percent) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Percent != 0) hash ^= Percent.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Percent != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Percent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Percent != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Percent);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Percent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Percent);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RateColor other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Percent != 0) {
        Percent = other.Percent;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Percent = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Percent = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class HistoryRoll : pb::IMessage<HistoryRoll>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<HistoryRoll> _parser = new pb::MessageParser<HistoryRoll>(() => new HistoryRoll());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<HistoryRoll> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HistoryRoll() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HistoryRoll(HistoryRoll other) : this() {
      listColors_ = other.listColors_.Clone();
      rateColors_ = other.rateColors_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public HistoryRoll Clone() {
      return new HistoryRoll(this);
    }

    /// <summary>Field number for the "list_colors" field.</summary>
    public const int ListColorsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Api.ListColor> _repeated_listColors_codec
        = pb::FieldCodec.ForMessage(10, global::Api.ListColor.Parser);
    private readonly pbc::RepeatedField<global::Api.ListColor> listColors_ = new pbc::RepeatedField<global::Api.ListColor>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.ListColor> ListColors {
      get { return listColors_; }
    }

    /// <summary>Field number for the "rate_colors" field.</summary>
    public const int RateColorsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Api.RateColor> _repeated_rateColors_codec
        = pb::FieldCodec.ForMessage(18, global::Api.RateColor.Parser);
    private readonly pbc::RepeatedField<global::Api.RateColor> rateColors_ = new pbc::RepeatedField<global::Api.RateColor>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.RateColor> RateColors {
      get { return rateColors_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as HistoryRoll);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(HistoryRoll other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!listColors_.Equals(other.listColors_)) return false;
      if(!rateColors_.Equals(other.rateColors_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= listColors_.GetHashCode();
      hash ^= rateColors_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      listColors_.WriteTo(output, _repeated_listColors_codec);
      rateColors_.WriteTo(output, _repeated_rateColors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      listColors_.WriteTo(ref output, _repeated_listColors_codec);
      rateColors_.WriteTo(ref output, _repeated_rateColors_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += listColors_.CalculateSize(_repeated_listColors_codec);
      size += rateColors_.CalculateSize(_repeated_rateColors_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(HistoryRoll other) {
      if (other == null) {
        return;
      }
      listColors_.Add(other.listColors_);
      rateColors_.Add(other.rateColors_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            listColors_.AddEntriesFrom(input, _repeated_listColors_codec);
            break;
          }
          case 18: {
            rateColors_.AddEntriesFrom(input, _repeated_rateColors_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            listColors_.AddEntriesFrom(ref input, _repeated_listColors_codec);
            break;
          }
          case 18: {
            rateColors_.AddEntriesFrom(ref input, _repeated_rateColors_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class InfoBet : pb::IMessage<InfoBet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<InfoBet> _parser = new pb::MessageParser<InfoBet>(() => new InfoBet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<InfoBet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InfoBet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InfoBet(InfoBet other) : this() {
      id_ = other.id_;
      chips_ = other.chips_;
      nUserBet_ = other.nUserBet_;
      desp_ = other.desp_;
      reqSpecGame_ = other.reqSpecGame_;
      emitNewgameEvent_ = other.emitNewgameEvent_;
      delayEmitResult_ = other.delayEmitResult_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public InfoBet Clone() {
      return new InfoBet(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "chips" field.</summary>
    public const int ChipsFieldNumber = 2;
    private long chips_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Chips {
      get { return chips_; }
      set {
        chips_ = value;
      }
    }

    /// <summary>Field number for the "n_user_bet" field.</summary>
    public const int NUserBetFieldNumber = 3;
    private int nUserBet_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NUserBet {
      get { return nUserBet_; }
      set {
        nUserBet_ = value;
      }
    }

    /// <summary>Field number for the "desp" field.</summary>
    public const int DespFieldNumber = 4;
    private string desp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desp {
      get { return desp_; }
      set {
        desp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "req_spec_game" field.</summary>
    public const int ReqSpecGameFieldNumber = 5;
    private int reqSpecGame_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ReqSpecGame {
      get { return reqSpecGame_; }
      set {
        reqSpecGame_ = value;
      }
    }

    /// <summary>Field number for the "emit_newgame_event" field.</summary>
    public const int EmitNewgameEventFieldNumber = 6;
    private bool emitNewgameEvent_;
    /// <summary>
    /// broadcast new game data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool EmitNewgameEvent {
      get { return emitNewgameEvent_; }
      set {
        emitNewgameEvent_ = value;
      }
    }

    /// <summary>Field number for the "delay_emit_result" field.</summary>
    public const int DelayEmitResultFieldNumber = 7;
    private string delayEmitResult_ = "";
    /// <summary>
    /// delay broadcast result endgame, unit 1s,1m, 1h, golang durationformat
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string DelayEmitResult {
      get { return delayEmitResult_; }
      set {
        delayEmitResult_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as InfoBet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(InfoBet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Chips != other.Chips) return false;
      if (NUserBet != other.NUserBet) return false;
      if (Desp != other.Desp) return false;
      if (ReqSpecGame != other.ReqSpecGame) return false;
      if (EmitNewgameEvent != other.EmitNewgameEvent) return false;
      if (DelayEmitResult != other.DelayEmitResult) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Chips != 0L) hash ^= Chips.GetHashCode();
      if (NUserBet != 0) hash ^= NUserBet.GetHashCode();
      if (Desp.Length != 0) hash ^= Desp.GetHashCode();
      if (ReqSpecGame != 0) hash ^= ReqSpecGame.GetHashCode();
      if (EmitNewgameEvent != false) hash ^= EmitNewgameEvent.GetHashCode();
      if (DelayEmitResult.Length != 0) hash ^= DelayEmitResult.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Chips != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Chips);
      }
      if (NUserBet != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NUserBet);
      }
      if (Desp.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Desp);
      }
      if (ReqSpecGame != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ReqSpecGame);
      }
      if (EmitNewgameEvent != false) {
        output.WriteRawTag(48);
        output.WriteBool(EmitNewgameEvent);
      }
      if (DelayEmitResult.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DelayEmitResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Chips != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Chips);
      }
      if (NUserBet != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NUserBet);
      }
      if (Desp.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Desp);
      }
      if (ReqSpecGame != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ReqSpecGame);
      }
      if (EmitNewgameEvent != false) {
        output.WriteRawTag(48);
        output.WriteBool(EmitNewgameEvent);
      }
      if (DelayEmitResult.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(DelayEmitResult);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Chips != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Chips);
      }
      if (NUserBet != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NUserBet);
      }
      if (Desp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desp);
      }
      if (ReqSpecGame != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ReqSpecGame);
      }
      if (EmitNewgameEvent != false) {
        size += 1 + 1;
      }
      if (DelayEmitResult.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DelayEmitResult);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(InfoBet other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Chips != 0L) {
        Chips = other.Chips;
      }
      if (other.NUserBet != 0) {
        NUserBet = other.NUserBet;
      }
      if (other.Desp.Length != 0) {
        Desp = other.Desp;
      }
      if (other.ReqSpecGame != 0) {
        ReqSpecGame = other.ReqSpecGame;
      }
      if (other.EmitNewgameEvent != false) {
        EmitNewgameEvent = other.EmitNewgameEvent;
      }
      if (other.DelayEmitResult.Length != 0) {
        DelayEmitResult = other.DelayEmitResult;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Chips = input.ReadInt64();
            break;
          }
          case 24: {
            NUserBet = input.ReadInt32();
            break;
          }
          case 34: {
            Desp = input.ReadString();
            break;
          }
          case 40: {
            ReqSpecGame = input.ReadInt32();
            break;
          }
          case 48: {
            EmitNewgameEvent = input.ReadBool();
            break;
          }
          case 58: {
            DelayEmitResult = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Chips = input.ReadInt64();
            break;
          }
          case 24: {
            NUserBet = input.ReadInt32();
            break;
          }
          case 34: {
            Desp = input.ReadString();
            break;
          }
          case 40: {
            ReqSpecGame = input.ReadInt32();
            break;
          }
          case 48: {
            EmitNewgameEvent = input.ReadBool();
            break;
          }
          case 58: {
            DelayEmitResult = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ListInfoBet : pb::IMessage<ListInfoBet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ListInfoBet> _parser = new pb::MessageParser<ListInfoBet>(() => new ListInfoBet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ListInfoBet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListInfoBet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListInfoBet(ListInfoBet other) : this() {
      listBets_ = other.listBets_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ListInfoBet Clone() {
      return new ListInfoBet(this);
    }

    /// <summary>Field number for the "list_bets" field.</summary>
    public const int ListBetsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Api.InfoBet> _repeated_listBets_codec
        = pb::FieldCodec.ForMessage(10, global::Api.InfoBet.Parser);
    private readonly pbc::RepeatedField<global::Api.InfoBet> listBets_ = new pbc::RepeatedField<global::Api.InfoBet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.InfoBet> ListBets {
      get { return listBets_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ListInfoBet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ListInfoBet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!listBets_.Equals(other.listBets_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= listBets_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      listBets_.WriteTo(output, _repeated_listBets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      listBets_.WriteTo(ref output, _repeated_listBets_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += listBets_.CalculateSize(_repeated_listBets_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ListInfoBet other) {
      if (other == null) {
        return;
      }
      listBets_.Add(other.listBets_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            listBets_.AddEntriesFrom(input, _repeated_listBets_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            listBets_.AddEntriesFrom(ref input, _repeated_listBets_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateDesk : pb::IMessage<UpdateDesk>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateDesk> _parser = new pb::MessageParser<UpdateDesk>(() => new UpdateDesk());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateDesk> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Api.ColorGameReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateDesk() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateDesk(UpdateDesk other) : this() {
      nPlayer_ = other.nPlayer_;
      updateUserBets_ = other.updateUserBets_;
      updateCellBets_ = other.updateCellBets_;
      userBets_ = other.userBets_.Clone();
      cellBets_ = other.cellBets_.Clone();
      updateHistoryRoll_ = other.updateHistoryRoll_;
      historyRolls_ = other.historyRolls_ != null ? other.historyRolls_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateDesk Clone() {
      return new UpdateDesk(this);
    }

    /// <summary>Field number for the "n_player" field.</summary>
    public const int NPlayerFieldNumber = 1;
    private int nPlayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NPlayer {
      get { return nPlayer_; }
      set {
        nPlayer_ = value;
      }
    }

    /// <summary>Field number for the "update_user_bets" field.</summary>
    public const int UpdateUserBetsFieldNumber = 2;
    private bool updateUserBets_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UpdateUserBets {
      get { return updateUserBets_; }
      set {
        updateUserBets_ = value;
      }
    }

    /// <summary>Field number for the "update_cell_bets" field.</summary>
    public const int UpdateCellBetsFieldNumber = 3;
    private bool updateCellBets_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UpdateCellBets {
      get { return updateCellBets_; }
      set {
        updateCellBets_ = value;
      }
    }

    /// <summary>Field number for the "user_bets" field.</summary>
    public const int UserBetsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Api.InfoBet> _repeated_userBets_codec
        = pb::FieldCodec.ForMessage(34, global::Api.InfoBet.Parser);
    private readonly pbc::RepeatedField<global::Api.InfoBet> userBets_ = new pbc::RepeatedField<global::Api.InfoBet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.InfoBet> UserBets {
      get { return userBets_; }
    }

    /// <summary>Field number for the "cell_bets" field.</summary>
    public const int CellBetsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Api.InfoBet> _repeated_cellBets_codec
        = pb::FieldCodec.ForMessage(42, global::Api.InfoBet.Parser);
    private readonly pbc::RepeatedField<global::Api.InfoBet> cellBets_ = new pbc::RepeatedField<global::Api.InfoBet>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Api.InfoBet> CellBets {
      get { return cellBets_; }
    }

    /// <summary>Field number for the "update_history_roll" field.</summary>
    public const int UpdateHistoryRollFieldNumber = 6;
    private bool updateHistoryRoll_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UpdateHistoryRoll {
      get { return updateHistoryRoll_; }
      set {
        updateHistoryRoll_ = value;
      }
    }

    /// <summary>Field number for the "history_rolls" field.</summary>
    public const int HistoryRollsFieldNumber = 7;
    private global::Api.HistoryRoll historyRolls_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Api.HistoryRoll HistoryRolls {
      get { return historyRolls_; }
      set {
        historyRolls_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateDesk);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateDesk other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (NPlayer != other.NPlayer) return false;
      if (UpdateUserBets != other.UpdateUserBets) return false;
      if (UpdateCellBets != other.UpdateCellBets) return false;
      if(!userBets_.Equals(other.userBets_)) return false;
      if(!cellBets_.Equals(other.cellBets_)) return false;
      if (UpdateHistoryRoll != other.UpdateHistoryRoll) return false;
      if (!object.Equals(HistoryRolls, other.HistoryRolls)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (NPlayer != 0) hash ^= NPlayer.GetHashCode();
      if (UpdateUserBets != false) hash ^= UpdateUserBets.GetHashCode();
      if (UpdateCellBets != false) hash ^= UpdateCellBets.GetHashCode();
      hash ^= userBets_.GetHashCode();
      hash ^= cellBets_.GetHashCode();
      if (UpdateHistoryRoll != false) hash ^= UpdateHistoryRoll.GetHashCode();
      if (historyRolls_ != null) hash ^= HistoryRolls.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (NPlayer != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NPlayer);
      }
      if (UpdateUserBets != false) {
        output.WriteRawTag(16);
        output.WriteBool(UpdateUserBets);
      }
      if (UpdateCellBets != false) {
        output.WriteRawTag(24);
        output.WriteBool(UpdateCellBets);
      }
      userBets_.WriteTo(output, _repeated_userBets_codec);
      cellBets_.WriteTo(output, _repeated_cellBets_codec);
      if (UpdateHistoryRoll != false) {
        output.WriteRawTag(48);
        output.WriteBool(UpdateHistoryRoll);
      }
      if (historyRolls_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HistoryRolls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (NPlayer != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(NPlayer);
      }
      if (UpdateUserBets != false) {
        output.WriteRawTag(16);
        output.WriteBool(UpdateUserBets);
      }
      if (UpdateCellBets != false) {
        output.WriteRawTag(24);
        output.WriteBool(UpdateCellBets);
      }
      userBets_.WriteTo(ref output, _repeated_userBets_codec);
      cellBets_.WriteTo(ref output, _repeated_cellBets_codec);
      if (UpdateHistoryRoll != false) {
        output.WriteRawTag(48);
        output.WriteBool(UpdateHistoryRoll);
      }
      if (historyRolls_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(HistoryRolls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (NPlayer != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NPlayer);
      }
      if (UpdateUserBets != false) {
        size += 1 + 1;
      }
      if (UpdateCellBets != false) {
        size += 1 + 1;
      }
      size += userBets_.CalculateSize(_repeated_userBets_codec);
      size += cellBets_.CalculateSize(_repeated_cellBets_codec);
      if (UpdateHistoryRoll != false) {
        size += 1 + 1;
      }
      if (historyRolls_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(HistoryRolls);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateDesk other) {
      if (other == null) {
        return;
      }
      if (other.NPlayer != 0) {
        NPlayer = other.NPlayer;
      }
      if (other.UpdateUserBets != false) {
        UpdateUserBets = other.UpdateUserBets;
      }
      if (other.UpdateCellBets != false) {
        UpdateCellBets = other.UpdateCellBets;
      }
      userBets_.Add(other.userBets_);
      cellBets_.Add(other.cellBets_);
      if (other.UpdateHistoryRoll != false) {
        UpdateHistoryRoll = other.UpdateHistoryRoll;
      }
      if (other.historyRolls_ != null) {
        if (historyRolls_ == null) {
          HistoryRolls = new global::Api.HistoryRoll();
        }
        HistoryRolls.MergeFrom(other.HistoryRolls);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            NPlayer = input.ReadInt32();
            break;
          }
          case 16: {
            UpdateUserBets = input.ReadBool();
            break;
          }
          case 24: {
            UpdateCellBets = input.ReadBool();
            break;
          }
          case 34: {
            userBets_.AddEntriesFrom(input, _repeated_userBets_codec);
            break;
          }
          case 42: {
            cellBets_.AddEntriesFrom(input, _repeated_cellBets_codec);
            break;
          }
          case 48: {
            UpdateHistoryRoll = input.ReadBool();
            break;
          }
          case 58: {
            if (historyRolls_ == null) {
              HistoryRolls = new global::Api.HistoryRoll();
            }
            input.ReadMessage(HistoryRolls);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            NPlayer = input.ReadInt32();
            break;
          }
          case 16: {
            UpdateUserBets = input.ReadBool();
            break;
          }
          case 24: {
            UpdateCellBets = input.ReadBool();
            break;
          }
          case 34: {
            userBets_.AddEntriesFrom(ref input, _repeated_userBets_codec);
            break;
          }
          case 42: {
            cellBets_.AddEntriesFrom(ref input, _repeated_cellBets_codec);
            break;
          }
          case 48: {
            UpdateHistoryRoll = input.ReadBool();
            break;
          }
          case 58: {
            if (historyRolls_ == null) {
              HistoryRolls = new global::Api.HistoryRoll();
            }
            input.ReadMessage(HistoryRolls);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
