// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: whot_game.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from whot_game.proto</summary>
  public static partial class WhotGameReflection {

    #region Descriptor
    /// <summary>File descriptor for whot_game.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WhotGameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg93aG90X2dhbWUucHJvdG8SBXByb3RvIlAKCFdob3RDYXJkEiEKBHJhbmsY",
            "ASABKA4yEy5wcm90by5XaG90Q2FyZFJhbmsSIQoEc3VpdBgCIAEoDjITLnBy",
            "b3RvLldob3RDYXJkU3VpdCIwCgpVcGRhdGVUdXJuEg8KB3VzZXJfaWQYASAB",
            "KAkSEQoJY291bnRkb3duGAIgASgDIrgDCg9VcGRhdGVDYXJkU3RhdGUSDwoH",
            "dXNlcl9pZBgBIAEoCRIjCgVldmVudBgCIAEoDjIULnByb3RvLldob3RDYXJk",
            "RXZlbnQSJAoLcGxheWVkX2NhcmQYAyABKAsyDy5wcm90by5XaG90Q2FyZBIh",
            "Cgh0b3BfY2FyZBgEIAEoCzIPLnByb3RvLldob3RDYXJkEiQKC2NhcmRzX2Fm",
            "dGVyGAUgAygLMg8ucHJvdG8uV2hvdENhcmQSJQoGZWZmZWN0GAYgASgOMhUu",
            "cHJvdG8uV2hvdENhcmRFZmZlY3QSFAoMcGlja19wZW5hbHR5GAcgASgFEhYK",
            "DnRhcmdldF91c2VyX2lkGAggASgJEhQKDGlzX2F1dG9fcGxheRgJIAEoCBIS",
            "CgpkZWNrX2NvdW50GAogASgFEkgKEnBsYXllcl9jYXJkX2NvdW50cxgLIAMo",
            "CzIsLnByb3RvLlVwZGF0ZUNhcmRTdGF0ZS5QbGF5ZXJDYXJkQ291bnRzRW50",
            "cnkaNwoVUGxheWVyQ2FyZENvdW50c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2",
            "YWx1ZRgCIAEoBToCOAEiigEKEFdob3RQbGF5ZXJSZXN1bHQSDwoHdXNlcl9p",
            "ZBgBIAEoCRIUCgx0b3RhbF9wb2ludHMYAiABKAMSEgoKd2luX2ZhY3RvchgD",
            "IAEoARIRCglpc193aW5uZXIYBCABKAgSKAoPcmVtYWluaW5nX2NhcmRzGAUg",
            "AygLMg8ucHJvdG8uV2hvdENhcmQqlgEKDFdob3RDYXJkU3VpdBIZChVXSE9U",
            "X1NVSVRfVU5TUEVDSUZJRUQQABIUChBXSE9UX1NVSVRfQ0lSQ0xFEAESEwoP",
            "V0hPVF9TVUlUX0NST1NTEAISEgoOV0hPVF9TVUlUX1NUQVIQAxIUChBXSE9U",
            "X1NVSVRfU1FVQVJFEAQSFgoSV0hPVF9TVUlUX1RSSUFOR0xFEAUqjAIKDFdo",
            "b3RDYXJkUmFuaxIZChVXSE9UX1JBTktfVU5TUEVDSUZJRUQQABIPCgtXSE9U",
            "X1JBTktfMRABEg8KC1dIT1RfUkFOS18yEAISDwoLV0hPVF9SQU5LXzMQAxIP",
            "CgtXSE9UX1JBTktfNBAEEg8KC1dIT1RfUkFOS181EAUSDwoLV0hPVF9SQU5L",
            "XzcQBxIPCgtXSE9UX1JBTktfOBAIEhAKDFdIT1RfUkFOS18xMBAKEhAKDFdI",
            "T1RfUkFOS18xMRALEhAKDFdIT1RfUkFOS18xMhAMEhAKDFdIT1RfUkFOS18x",
            "MxANEhAKDFdIT1RfUkFOS18xNBAOEhAKDFdIT1RfUkFOS18yMBAUKn0KDVdo",
            "b3RDYXJkRXZlbnQSEwoPV0hPVF9FVkVOVF9OT05FEAASEwoPV0hPVF9FVkVO",
            "VF9QTEFZEAESEwoPV0hPVF9FVkVOVF9EUkFXEAISEwoPV0hPVF9FVkVOVF9Q",
            "QVNTEAMSGAoUV0hPVF9FVkVOVF9BVVRPX1BMQVkQBCqSAQoOV2hvdENhcmRF",
            "ZmZlY3QSDwoLRUZGRUNUX05PTkUQABILCgdIT0xEX09OEAESDAoIUElDS19U",
            "V08QAhIOCgpQSUNLX1RIUkVFEAMSDgoKU1VTUEVOU0lPThAEEhIKDkdFTkVS",
            "QUxfTUFSS0VUEAUSCAoEV0hPVBAGEhYKEkNIT0lDRV9TSEFQRV9HSE9TVBAH",
            "QihaJmdpdGh1Yi5jb20vbmstbmlnZXJpYS9jZ3AtY29tbW9uL3Byb3RvYgZw",
            "cm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.WhotCardSuit), typeof(global::Proto.WhotCardRank), typeof(global::Proto.WhotCardEvent), typeof(global::Proto.WhotCardEffect), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.WhotCard), global::Proto.WhotCard.Parser, new[]{ "Rank", "Suit" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.UpdateTurn), global::Proto.UpdateTurn.Parser, new[]{ "UserId", "Countdown" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.UpdateCardState), global::Proto.UpdateCardState.Parser, new[]{ "UserId", "Event", "PlayedCard", "TopCard", "CardsAfter", "Effect", "PickPenalty", "TargetUserId", "IsAutoPlay", "DeckCount", "PlayerCardCounts" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.WhotPlayerResult), global::Proto.WhotPlayerResult.Parser, new[]{ "UserId", "TotalPoints", "WinFactor", "IsWinner", "RemainingCards" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum WhotCardSuit {
    [pbr::OriginalName("WHOT_SUIT_UNSPECIFIED")] WhotSuitUnspecified = 0,
    [pbr::OriginalName("WHOT_SUIT_CIRCLE")] WhotSuitCircle = 1,
    [pbr::OriginalName("WHOT_SUIT_CROSS")] WhotSuitCross = 2,
    [pbr::OriginalName("WHOT_SUIT_STAR")] WhotSuitStar = 3,
    [pbr::OriginalName("WHOT_SUIT_SQUARE")] WhotSuitSquare = 4,
    [pbr::OriginalName("WHOT_SUIT_TRIANGLE")] WhotSuitTriangle = 5,
  }

  public enum WhotCardRank {
    [pbr::OriginalName("WHOT_RANK_UNSPECIFIED")] WhotRankUnspecified = 0,
    [pbr::OriginalName("WHOT_RANK_1")] WhotRank1 = 1,
    [pbr::OriginalName("WHOT_RANK_2")] WhotRank2 = 2,
    [pbr::OriginalName("WHOT_RANK_3")] WhotRank3 = 3,
    [pbr::OriginalName("WHOT_RANK_4")] WhotRank4 = 4,
    [pbr::OriginalName("WHOT_RANK_5")] WhotRank5 = 5,
    [pbr::OriginalName("WHOT_RANK_7")] WhotRank7 = 7,
    [pbr::OriginalName("WHOT_RANK_8")] WhotRank8 = 8,
    [pbr::OriginalName("WHOT_RANK_10")] WhotRank10 = 10,
    [pbr::OriginalName("WHOT_RANK_11")] WhotRank11 = 11,
    [pbr::OriginalName("WHOT_RANK_12")] WhotRank12 = 12,
    [pbr::OriginalName("WHOT_RANK_13")] WhotRank13 = 13,
    [pbr::OriginalName("WHOT_RANK_14")] WhotRank14 = 14,
    [pbr::OriginalName("WHOT_RANK_20")] WhotRank20 = 20,
  }

  public enum WhotCardEvent {
    [pbr::OriginalName("WHOT_EVENT_NONE")] WhotEventNone = 0,
    [pbr::OriginalName("WHOT_EVENT_PLAY")] WhotEventPlay = 1,
    [pbr::OriginalName("WHOT_EVENT_DRAW")] WhotEventDraw = 2,
    [pbr::OriginalName("WHOT_EVENT_PASS")] WhotEventPass = 3,
    [pbr::OriginalName("WHOT_EVENT_AUTO_PLAY")] WhotEventAutoPlay = 4,
  }

  public enum WhotCardEffect {
    [pbr::OriginalName("EFFECT_NONE")] EffectNone = 0,
    [pbr::OriginalName("HOLD_ON")] HoldOn = 1,
    [pbr::OriginalName("PICK_TWO")] PickTwo = 2,
    [pbr::OriginalName("PICK_THREE")] PickThree = 3,
    [pbr::OriginalName("SUSPENSION")] Suspension = 4,
    [pbr::OriginalName("GENERAL_MARKET")] GeneralMarket = 5,
    [pbr::OriginalName("WHOT")] Whot = 6,
    [pbr::OriginalName("CHOICE_SHAPE_GHOST")] ChoiceShapeGhost = 7,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WhotCard : pb::IMessage<WhotCard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WhotCard> _parser = new pb::MessageParser<WhotCard>(() => new WhotCard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WhotCard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.WhotGameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhotCard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhotCard(WhotCard other) : this() {
      rank_ = other.rank_;
      suit_ = other.suit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhotCard Clone() {
      return new WhotCard(this);
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 1;
    private global::Proto.WhotCardRank rank_ = global::Proto.WhotCardRank.WhotRankUnspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.WhotCardRank Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "suit" field.</summary>
    public const int SuitFieldNumber = 2;
    private global::Proto.WhotCardSuit suit_ = global::Proto.WhotCardSuit.WhotSuitUnspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.WhotCardSuit Suit {
      get { return suit_; }
      set {
        suit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WhotCard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WhotCard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Rank != other.Rank) return false;
      if (Suit != other.Suit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Rank != global::Proto.WhotCardRank.WhotRankUnspecified) hash ^= Rank.GetHashCode();
      if (Suit != global::Proto.WhotCardSuit.WhotSuitUnspecified) hash ^= Suit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Rank != global::Proto.WhotCardRank.WhotRankUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Rank);
      }
      if (Suit != global::Proto.WhotCardSuit.WhotSuitUnspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Suit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Rank != global::Proto.WhotCardRank.WhotRankUnspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Rank);
      }
      if (Suit != global::Proto.WhotCardSuit.WhotSuitUnspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Suit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Rank != global::Proto.WhotCardRank.WhotRankUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Rank);
      }
      if (Suit != global::Proto.WhotCardSuit.WhotSuitUnspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Suit);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WhotCard other) {
      if (other == null) {
        return;
      }
      if (other.Rank != global::Proto.WhotCardRank.WhotRankUnspecified) {
        Rank = other.Rank;
      }
      if (other.Suit != global::Proto.WhotCardSuit.WhotSuitUnspecified) {
        Suit = other.Suit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Rank = (global::Proto.WhotCardRank) input.ReadEnum();
            break;
          }
          case 16: {
            Suit = (global::Proto.WhotCardSuit) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Rank = (global::Proto.WhotCardRank) input.ReadEnum();
            break;
          }
          case 16: {
            Suit = (global::Proto.WhotCardSuit) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateTurn : pb::IMessage<UpdateTurn>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateTurn> _parser = new pb::MessageParser<UpdateTurn>(() => new UpdateTurn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateTurn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.WhotGameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateTurn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateTurn(UpdateTurn other) : this() {
      userId_ = other.userId_;
      countdown_ = other.countdown_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateTurn Clone() {
      return new UpdateTurn(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "countdown" field.</summary>
    public const int CountdownFieldNumber = 2;
    private long countdown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Countdown {
      get { return countdown_; }
      set {
        countdown_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateTurn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateTurn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (Countdown != other.Countdown) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Countdown != 0L) hash ^= Countdown.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Countdown != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Countdown != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Countdown);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Countdown != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Countdown);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateTurn other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Countdown != 0L) {
        Countdown = other.Countdown;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            Countdown = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            Countdown = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateCardState : pb::IMessage<UpdateCardState>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateCardState> _parser = new pb::MessageParser<UpdateCardState>(() => new UpdateCardState());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateCardState> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.WhotGameReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateCardState() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateCardState(UpdateCardState other) : this() {
      userId_ = other.userId_;
      event_ = other.event_;
      playedCard_ = other.playedCard_ != null ? other.playedCard_.Clone() : null;
      topCard_ = other.topCard_ != null ? other.topCard_.Clone() : null;
      cardsAfter_ = other.cardsAfter_.Clone();
      effect_ = other.effect_;
      pickPenalty_ = other.pickPenalty_;
      targetUserId_ = other.targetUserId_;
      isAutoPlay_ = other.isAutoPlay_;
      deckCount_ = other.deckCount_;
      playerCardCounts_ = other.playerCardCounts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateCardState Clone() {
      return new UpdateCardState(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "event" field.</summary>
    public const int EventFieldNumber = 2;
    private global::Proto.WhotCardEvent event_ = global::Proto.WhotCardEvent.WhotEventNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.WhotCardEvent Event {
      get { return event_; }
      set {
        event_ = value;
      }
    }

    /// <summary>Field number for the "played_card" field.</summary>
    public const int PlayedCardFieldNumber = 3;
    private global::Proto.WhotCard playedCard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.WhotCard PlayedCard {
      get { return playedCard_; }
      set {
        playedCard_ = value;
      }
    }

    /// <summary>Field number for the "top_card" field.</summary>
    public const int TopCardFieldNumber = 4;
    private global::Proto.WhotCard topCard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.WhotCard TopCard {
      get { return topCard_; }
      set {
        topCard_ = value;
      }
    }

    /// <summary>Field number for the "cards_after" field.</summary>
    public const int CardsAfterFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Proto.WhotCard> _repeated_cardsAfter_codec
        = pb::FieldCodec.ForMessage(42, global::Proto.WhotCard.Parser);
    private readonly pbc::RepeatedField<global::Proto.WhotCard> cardsAfter_ = new pbc::RepeatedField<global::Proto.WhotCard>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.WhotCard> CardsAfter {
      get { return cardsAfter_; }
    }

    /// <summary>Field number for the "effect" field.</summary>
    public const int EffectFieldNumber = 6;
    private global::Proto.WhotCardEffect effect_ = global::Proto.WhotCardEffect.EffectNone;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Proto.WhotCardEffect Effect {
      get { return effect_; }
      set {
        effect_ = value;
      }
    }

    /// <summary>Field number for the "pick_penalty" field.</summary>
    public const int PickPenaltyFieldNumber = 7;
    private int pickPenalty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PickPenalty {
      get { return pickPenalty_; }
      set {
        pickPenalty_ = value;
      }
    }

    /// <summary>Field number for the "target_user_id" field.</summary>
    public const int TargetUserIdFieldNumber = 8;
    private string targetUserId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TargetUserId {
      get { return targetUserId_; }
      set {
        targetUserId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "is_auto_play" field.</summary>
    public const int IsAutoPlayFieldNumber = 9;
    private bool isAutoPlay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAutoPlay {
      get { return isAutoPlay_; }
      set {
        isAutoPlay_ = value;
      }
    }

    /// <summary>Field number for the "deck_count" field.</summary>
    public const int DeckCountFieldNumber = 10;
    private int deckCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DeckCount {
      get { return deckCount_; }
      set {
        deckCount_ = value;
      }
    }

    /// <summary>Field number for the "player_card_counts" field.</summary>
    public const int PlayerCardCountsFieldNumber = 11;
    private static readonly pbc::MapField<string, int>.Codec _map_playerCardCounts_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 90);
    private readonly pbc::MapField<string, int> playerCardCounts_ = new pbc::MapField<string, int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> PlayerCardCounts {
      get { return playerCardCounts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateCardState);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateCardState other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (Event != other.Event) return false;
      if (!object.Equals(PlayedCard, other.PlayedCard)) return false;
      if (!object.Equals(TopCard, other.TopCard)) return false;
      if(!cardsAfter_.Equals(other.cardsAfter_)) return false;
      if (Effect != other.Effect) return false;
      if (PickPenalty != other.PickPenalty) return false;
      if (TargetUserId != other.TargetUserId) return false;
      if (IsAutoPlay != other.IsAutoPlay) return false;
      if (DeckCount != other.DeckCount) return false;
      if (!PlayerCardCounts.Equals(other.PlayerCardCounts)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (Event != global::Proto.WhotCardEvent.WhotEventNone) hash ^= Event.GetHashCode();
      if (playedCard_ != null) hash ^= PlayedCard.GetHashCode();
      if (topCard_ != null) hash ^= TopCard.GetHashCode();
      hash ^= cardsAfter_.GetHashCode();
      if (Effect != global::Proto.WhotCardEffect.EffectNone) hash ^= Effect.GetHashCode();
      if (PickPenalty != 0) hash ^= PickPenalty.GetHashCode();
      if (TargetUserId.Length != 0) hash ^= TargetUserId.GetHashCode();
      if (IsAutoPlay != false) hash ^= IsAutoPlay.GetHashCode();
      if (DeckCount != 0) hash ^= DeckCount.GetHashCode();
      hash ^= PlayerCardCounts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Event != global::Proto.WhotCardEvent.WhotEventNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Event);
      }
      if (playedCard_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayedCard);
      }
      if (topCard_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TopCard);
      }
      cardsAfter_.WriteTo(output, _repeated_cardsAfter_codec);
      if (Effect != global::Proto.WhotCardEffect.EffectNone) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Effect);
      }
      if (PickPenalty != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(PickPenalty);
      }
      if (TargetUserId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TargetUserId);
      }
      if (IsAutoPlay != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsAutoPlay);
      }
      if (DeckCount != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(DeckCount);
      }
      playerCardCounts_.WriteTo(output, _map_playerCardCounts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (Event != global::Proto.WhotCardEvent.WhotEventNone) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Event);
      }
      if (playedCard_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PlayedCard);
      }
      if (topCard_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(TopCard);
      }
      cardsAfter_.WriteTo(ref output, _repeated_cardsAfter_codec);
      if (Effect != global::Proto.WhotCardEffect.EffectNone) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Effect);
      }
      if (PickPenalty != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(PickPenalty);
      }
      if (TargetUserId.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(TargetUserId);
      }
      if (IsAutoPlay != false) {
        output.WriteRawTag(72);
        output.WriteBool(IsAutoPlay);
      }
      if (DeckCount != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(DeckCount);
      }
      playerCardCounts_.WriteTo(ref output, _map_playerCardCounts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (Event != global::Proto.WhotCardEvent.WhotEventNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Event);
      }
      if (playedCard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PlayedCard);
      }
      if (topCard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TopCard);
      }
      size += cardsAfter_.CalculateSize(_repeated_cardsAfter_codec);
      if (Effect != global::Proto.WhotCardEffect.EffectNone) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Effect);
      }
      if (PickPenalty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PickPenalty);
      }
      if (TargetUserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TargetUserId);
      }
      if (IsAutoPlay != false) {
        size += 1 + 1;
      }
      if (DeckCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DeckCount);
      }
      size += playerCardCounts_.CalculateSize(_map_playerCardCounts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateCardState other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.Event != global::Proto.WhotCardEvent.WhotEventNone) {
        Event = other.Event;
      }
      if (other.playedCard_ != null) {
        if (playedCard_ == null) {
          PlayedCard = new global::Proto.WhotCard();
        }
        PlayedCard.MergeFrom(other.PlayedCard);
      }
      if (other.topCard_ != null) {
        if (topCard_ == null) {
          TopCard = new global::Proto.WhotCard();
        }
        TopCard.MergeFrom(other.TopCard);
      }
      cardsAfter_.Add(other.cardsAfter_);
      if (other.Effect != global::Proto.WhotCardEffect.EffectNone) {
        Effect = other.Effect;
      }
      if (other.PickPenalty != 0) {
        PickPenalty = other.PickPenalty;
      }
      if (other.TargetUserId.Length != 0) {
        TargetUserId = other.TargetUserId;
      }
      if (other.IsAutoPlay != false) {
        IsAutoPlay = other.IsAutoPlay;
      }
      if (other.DeckCount != 0) {
        DeckCount = other.DeckCount;
      }
      playerCardCounts_.Add(other.playerCardCounts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            Event = (global::Proto.WhotCardEvent) input.ReadEnum();
            break;
          }
          case 26: {
            if (playedCard_ == null) {
              PlayedCard = new global::Proto.WhotCard();
            }
            input.ReadMessage(PlayedCard);
            break;
          }
          case 34: {
            if (topCard_ == null) {
              TopCard = new global::Proto.WhotCard();
            }
            input.ReadMessage(TopCard);
            break;
          }
          case 42: {
            cardsAfter_.AddEntriesFrom(input, _repeated_cardsAfter_codec);
            break;
          }
          case 48: {
            Effect = (global::Proto.WhotCardEffect) input.ReadEnum();
            break;
          }
          case 56: {
            PickPenalty = input.ReadInt32();
            break;
          }
          case 66: {
            TargetUserId = input.ReadString();
            break;
          }
          case 72: {
            IsAutoPlay = input.ReadBool();
            break;
          }
          case 80: {
            DeckCount = input.ReadInt32();
            break;
          }
          case 90: {
            playerCardCounts_.AddEntriesFrom(input, _map_playerCardCounts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            Event = (global::Proto.WhotCardEvent) input.ReadEnum();
            break;
          }
          case 26: {
            if (playedCard_ == null) {
              PlayedCard = new global::Proto.WhotCard();
            }
            input.ReadMessage(PlayedCard);
            break;
          }
          case 34: {
            if (topCard_ == null) {
              TopCard = new global::Proto.WhotCard();
            }
            input.ReadMessage(TopCard);
            break;
          }
          case 42: {
            cardsAfter_.AddEntriesFrom(ref input, _repeated_cardsAfter_codec);
            break;
          }
          case 48: {
            Effect = (global::Proto.WhotCardEffect) input.ReadEnum();
            break;
          }
          case 56: {
            PickPenalty = input.ReadInt32();
            break;
          }
          case 66: {
            TargetUserId = input.ReadString();
            break;
          }
          case 72: {
            IsAutoPlay = input.ReadBool();
            break;
          }
          case 80: {
            DeckCount = input.ReadInt32();
            break;
          }
          case 90: {
            playerCardCounts_.AddEntriesFrom(ref input, _map_playerCardCounts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WhotPlayerResult : pb::IMessage<WhotPlayerResult>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WhotPlayerResult> _parser = new pb::MessageParser<WhotPlayerResult>(() => new WhotPlayerResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WhotPlayerResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.WhotGameReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhotPlayerResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhotPlayerResult(WhotPlayerResult other) : this() {
      userId_ = other.userId_;
      totalPoints_ = other.totalPoints_;
      winFactor_ = other.winFactor_;
      isWinner_ = other.isWinner_;
      remainingCards_ = other.remainingCards_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WhotPlayerResult Clone() {
      return new WhotPlayerResult(this);
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 1;
    private string userId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "total_points" field.</summary>
    public const int TotalPointsFieldNumber = 2;
    private long totalPoints_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalPoints {
      get { return totalPoints_; }
      set {
        totalPoints_ = value;
      }
    }

    /// <summary>Field number for the "win_factor" field.</summary>
    public const int WinFactorFieldNumber = 3;
    private double winFactor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double WinFactor {
      get { return winFactor_; }
      set {
        winFactor_ = value;
      }
    }

    /// <summary>Field number for the "is_winner" field.</summary>
    public const int IsWinnerFieldNumber = 4;
    private bool isWinner_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsWinner {
      get { return isWinner_; }
      set {
        isWinner_ = value;
      }
    }

    /// <summary>Field number for the "remaining_cards" field.</summary>
    public const int RemainingCardsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Proto.WhotCard> _repeated_remainingCards_codec
        = pb::FieldCodec.ForMessage(42, global::Proto.WhotCard.Parser);
    private readonly pbc::RepeatedField<global::Proto.WhotCard> remainingCards_ = new pbc::RepeatedField<global::Proto.WhotCard>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Proto.WhotCard> RemainingCards {
      get { return remainingCards_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WhotPlayerResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WhotPlayerResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (TotalPoints != other.TotalPoints) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(WinFactor, other.WinFactor)) return false;
      if (IsWinner != other.IsWinner) return false;
      if(!remainingCards_.Equals(other.remainingCards_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (TotalPoints != 0L) hash ^= TotalPoints.GetHashCode();
      if (WinFactor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(WinFactor);
      if (IsWinner != false) hash ^= IsWinner.GetHashCode();
      hash ^= remainingCards_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (TotalPoints != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalPoints);
      }
      if (WinFactor != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(WinFactor);
      }
      if (IsWinner != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsWinner);
      }
      remainingCards_.WriteTo(output, _repeated_remainingCards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserId);
      }
      if (TotalPoints != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalPoints);
      }
      if (WinFactor != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(WinFactor);
      }
      if (IsWinner != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsWinner);
      }
      remainingCards_.WriteTo(ref output, _repeated_remainingCards_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (TotalPoints != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalPoints);
      }
      if (WinFactor != 0D) {
        size += 1 + 8;
      }
      if (IsWinner != false) {
        size += 1 + 1;
      }
      size += remainingCards_.CalculateSize(_repeated_remainingCards_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WhotPlayerResult other) {
      if (other == null) {
        return;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.TotalPoints != 0L) {
        TotalPoints = other.TotalPoints;
      }
      if (other.WinFactor != 0D) {
        WinFactor = other.WinFactor;
      }
      if (other.IsWinner != false) {
        IsWinner = other.IsWinner;
      }
      remainingCards_.Add(other.remainingCards_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            TotalPoints = input.ReadInt64();
            break;
          }
          case 25: {
            WinFactor = input.ReadDouble();
            break;
          }
          case 32: {
            IsWinner = input.ReadBool();
            break;
          }
          case 42: {
            remainingCards_.AddEntriesFrom(input, _repeated_remainingCards_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserId = input.ReadString();
            break;
          }
          case 16: {
            TotalPoints = input.ReadInt64();
            break;
          }
          case 25: {
            WinFactor = input.ReadDouble();
            break;
          }
          case 32: {
            IsWinner = input.ReadBool();
            break;
          }
          case 42: {
            remainingCards_.AddEntriesFrom(ref input, _repeated_remainingCards_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
